### PR TITLE
Added missing type annotation for Ajv to Validator class

### LINKED ISSUE #67: TypeScript definitions are missing a type for Validator#ajv
This means that you will have no idea this property exists unless you notice it in the README: https://github.com/simonplend/express-json-validator-middleware#ajv-instance

Access to the Ajv instance is required for configuring Ajv plugins, so it's important that it's intuitive for users of this library to access i.e. by it having an explicit type definition.

### PR DESCRIPTION
**Pull request by NGTOne**
This resolves #67.

### CODE REVIEW

**Comment by simonplend** [comment]
@NGTOne Amazing, thank you so much for fixing this! :pray:

**Comment by simonplend** [comment]
@NGTOne Have you by any chance run into the issue raised here: https://github.com/simonplend/express-json-validator-middleware/issues/39?

**Comment by NGTOne** [comment]
> @NGTOne Have you by any chance run into the issue raised here: #39?

Repeatedly, in fact. I'll see if I can't take a gander at it this weekend.

**Comment by simonplend** [comment]
> Repeatedly, in fact. I'll see if I can't take a gander at it this weekend.

@NGTOne That would be great, thank you! Fixing that problem is a bit beyond my TypeScript knowledge at the moment unfortunately.

**Pull request merged**
