### PR TITLE
Possibility to use predefined schema for all validation checks (new ajv version as well)

### PR DESCRIPTION
**Pull request by w473**

### CODE REVIEW

**Comment by simonplend** [comment]
Hi @w473 :wave: I'm the new maintainer of this project.

Thank you so much for your contribution! This looks like a really nice feature addition.

I'm currently working on the [v2.2.0 release](https://github.com/vacekj/express-json-validator-middleware/milestone/1), but I'm intending to upgrade Ajv to v7 in a [v3.0.0 release](https://github.com/vacekj/express-json-validator-middleware/milestone/2). In regard to this pull request:

- I want the upgrade to Ajv v7 to be in its own pull request as its own clear set of changes. When I start working on the v3.0.0 release I will create a pull request which _only_ contains the upgrade to Ajv v7 and references you introducing the upgrade in this pull request (the `ajv-formats` note you have added in the `README` is :+1:).
- Once I've merged in the pull request for upgrading to Ajv v7, would you mind creating a new pull request containing only the predefined schema changes?

I think potentially all of the changes you've proposed here could go in the v3.0.0 release, but I would like to separate things out so they can be released separately if needed. It will also make for a cleaner history in git.

**Comment by w473** [comment]
>     * would you mind creating a new pull request

sure, no problem. I will then wait for 3.0.0

**Comment by simonplend** [comment]
@w473 Great, thank you :+1:

**Comment by simonplend** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
